/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-09-24 02:26:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class region_002dmaintener_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/Users/boyarce/Downloads/MySite/build/web/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153399482000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1566237122000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>REGION MAINTENER</title>\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/jsp/template/header.jsp", out, false);
      out.write("\n");
      out.write("    </head>\n");
      out.write("    <body>       \n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/jsp/template/menu.jsp", out, false);
      out.write("\n");
      out.write("        <div class=\"container\">        \n");
      out.write("            <form id=\"frm-login\" action=\"../CreateRegionServlet\" method=\"POST\">\n");
      out.write("                <div style=\"margin-top: 2.5%;margin-left: 15%; max-width: 600px\">\n");
      out.write("                    <h1>CREATE REGIÓN</h1>\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"form-group col-sm-12\">                        \n");
      out.write("                            <input type=\"text\" class=\"form-control\" id=\"txt-id\" placeholder=\"ID\"\n");
      out.write("                                   name=\"id\">\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"form-group col-sm-12\">                        \n");
      out.write("                            <input type=\"text\" class=\"form-control\" id=\"txt-nombre\" placeholder=\"NOMBRE\"\n");
      out.write("                                   name=\"nombre\">\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"form-group col-sm-12\">                        \n");
      out.write("                            <input type=\"text\" class=\"form-control\" id=\"txt-descripcion\" placeholder=\"DESCRIPCION\"\n");
      out.write("                                   name=\"descripcion\">\n");
      out.write("                        </div>\n");
      out.write("                    </div>                 \n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"form-group col-sm-8\">                        \n");
      out.write("                        </div>                 \n");
      out.write("                        <div class=\"form-group col-sm-4\">                        \n");
      out.write("                            <button id=\"bnt-calcular\" type=\"submit\" \n");
      out.write("                                    class=\"btn btn-success col-sm-12\">CREATE</button>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                    </div>                    \n");
      out.write("                </div>\n");
      out.write("                <div style=\"margin-top: 2.5%;margin-left: 8%;max-width:800px\">                    \n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <table class=\"table table-striped\">\n");
      out.write("                            <thead>\n");
      out.write("                                <tr>\n");
      out.write("                                    <th scope=\"col\">ID</th>\n");
      out.write("                                    <th scope=\"col\">NOMBRE</th>\n");
      out.write("                                    <th scope=\"col\">DESCRIPCION</th>\n");
      out.write("                                </tr>\n");
      out.write("                            </thead>                        \n");
      out.write("                            ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                        </table>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("    </body>\n");
      out.write("    <script>\n");
      out.write("        function load() {\n");
      out.write("            const Http = new XMLHttpRequest();\n");
      out.write("            const url = '../ListRegionServlet';\n");
      out.write("            Http.open('GET', url);\n");
      out.write("            Http.send();\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /**\n");
      out.write("         * Funcion encargada de editar la fila\n");
      out.write("         * @param {type} row\n");
      out.write("         * @returns {undefined}\n");
      out.write("         */\n");
      out.write("        function edit(row) {\n");
      out.write("\n");
      out.write("\n");
      out.write("            editRow(row, false, false, true, true,\n");
      out.write("                    false, false);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /**\n");
      out.write("         * Metodo encargado de cancelar la edicion de una fila\n");
      out.write("         * @param {type} row\n");
      out.write("         * @returns {undefined}\n");
      out.write("         */\n");
      out.write("        function cancelRow(row) {\n");
      out.write("            editRow(row, true, true, false, false,\n");
      out.write("                    true, true);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /*\n");
      out.write("         * Funcion que modifica componentes de una fila de la tabla con listado de regiones\n");
      out.write("         * @param {type} txtNombre\n");
      out.write("         * @param {type} txtDescripcion\n");
      out.write("         * @param {type} btnEdit\n");
      out.write("         * @param {type} btnDelete\n");
      out.write("         * @param {type} btnSave\n");
      out.write("         * @param {type} btnCancel\n");
      out.write("         * @param {type} nombreDisabled\n");
      out.write("         * @param {type} descripcionDisbled\n");
      out.write("         * @param {type} editDisabled\n");
      out.write("         * @param {type} deleteDisabled\n");
      out.write("         * @param {type} saveDisabled\n");
      out.write("         * @param {type} cancelDisabled\n");
      out.write("         * @returns {undefined}\n");
      out.write("         */\n");
      out.write("        function editRow(row, nombreDisabled, descripcionDisbled, editDisabled, deleteDisabled,\n");
      out.write("                saveDisabled, cancelDisabled) {\n");
      out.write("\n");
      out.write("            var txtNombre = \"txt-nombre-\" + row;\n");
      out.write("            var txtDescripcion = \"txt-descripcion-\" + row;\n");
      out.write("            var btnEdit = 'bnt-edit-' + row;\n");
      out.write("            var btnDelete = 'bnt-delete-' + row;\n");
      out.write("            var btnSave = 'bnt-save-' + row;\n");
      out.write("            var btnCancel = 'bnt-cancel-' + row;\n");
      out.write("\n");
      out.write("            document.getElementById(txtNombre).disabled = nombreDisabled;\n");
      out.write("            document.getElementById(txtDescripcion).disabled = descripcionDisbled;\n");
      out.write("            document.getElementById(btnEdit).hidden = editDisabled;\n");
      out.write("            document.getElementById(btnDelete).hidden = deleteDisabled;\n");
      out.write("            document.getElementById(btnSave).hidden = saveDisabled;\n");
      out.write("            document.getElementById(btnCancel).hidden = cancelDisabled;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /** Funcion encargada de modificar una region\n");
      out.write("         * \n");
      out.write("         * @param {type} row\n");
      out.write("         * @returns {undefined}\n");
      out.write("         */\n");
      out.write("        function saveRow(row) {\n");
      out.write("\n");
      out.write("            var id = document.getElementById(\"txt-id-\" + row).value;\n");
      out.write("            var nombre = document.getElementById(\"txt-nombre-\" + row).value;\n");
      out.write("            var descripcion = document.getElementById(\"txt-descripcion-\" + row).value;\n");
      out.write("            cancelRow(row);\n");
      out.write("            const Http = new XMLHttpRequest();\n");
      out.write("            const url = '../UpdateRegionServlet?id=' + id + '&nombre=' + nombre\n");
      out.write("                    + '&descripcion=' + descripcion;\n");
      out.write("            Http.open('GET', url);\n");
      out.write("            Http.send();\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function deleteRow(row) {\n");
      out.write("            var id = document.getElementById(\"txt-id-\" + row).value;\n");
      out.write("            cancelRow(row);\n");
      out.write("\n");
      out.write("            $.ajax({\n");
      out.write("                url: '../DeleteRegionServlet?id=' + id,\n");
      out.write("                method: 'GET',\n");
      out.write("                success: window.location.reload()\n");
      out.write("            });\n");
      out.write("\n");
      out.write("        }\n");
      out.write("\n");
      out.write("    </script>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /jsp/region-maintener.jsp(49,24) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty sessionScope.errorCreateRegion}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                            <div id=\"msg-error\" class=\"form-group col-sm-12 btn btn-danger\" style=\"font-size: 10px !important\">\n");
          out.write("                                ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.errorCreateRegion}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\n");
          out.write("                            </div>                    \n");
          out.write("                        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /jsp/region-maintener.jsp(66,28) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("region");
      // /jsp/region-maintener.jsp(66,28) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/jsp/region-maintener.jsp(66,28) '${regiones}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${regiones}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /jsp/region-maintener.jsp(66,28) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("i");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("                                <tr>\n");
            out.write("                                    <td>\n");
            out.write("                                        <input type=\"text\" class=\"form-control\" id=\"txt-id-");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\n");
            out.write("                                               placeholder=\"ID\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${region.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" disabled=\"true\"\n");
            out.write("                                               name=\"id\" style=\"font-size: 8px !important\">                                    \n");
            out.write("                                    </td>\n");
            out.write("                                    <td>\n");
            out.write("                                        <input type=\"text\" class=\"form-control\" id=\"txt-nombre-");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\n");
            out.write("                                               placeholder=\"ID\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${region.nombre}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" disabled=\"true\"\n");
            out.write("                                               name=\"id\" style=\"font-size: 8px !important\">                                        \n");
            out.write("                                    </td> \n");
            out.write("                                    <td>\n");
            out.write("                                        <input type=\"text\" class=\"form-control\" id=\"txt-descripcion-");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\n");
            out.write("                                               placeholder=\"ID\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${region.descripcion}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" disabled=\"true\"\n");
            out.write("                                               name=\"id\" style=\"font-size: 8px !important\">                                      \n");
            out.write("                                    </td>\n");
            out.write("                                    <td>\n");
            out.write("                                        <button id=\"bnt-edit-");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" type=\"button\" \n");
            out.write("                                                onclick=\"edit('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("')\"\n");
            out.write("                                                class=\"btn btn-warning col-sm-5\">EDIT</button>    \n");
            out.write("                                        <button id=\"bnt-delete-");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" type=\"button\" \n");
            out.write("                                                onclick=\"deleteRow('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("')\"                                               \n");
            out.write("                                                class=\"btn btn-danger col-sm-5\">DELETE</button>  \n");
            out.write("                                        <button id=\"bnt-save-");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" type=\"button\"\n");
            out.write("                                                onclick=\"saveRow('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("')\"                                                \n");
            out.write("                                                class=\"btn btn-success col-sm-5\" hidden=\"true\">SAVE</button>    \n");
            out.write("                                        <button id=\"bnt-cancel-");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" type=\"button\"\n");
            out.write("                                                onclick=\"cancelRow('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("')\"                                                \n");
            out.write("                                                class=\"btn btn-danger col-sm-5\" hidden=\"true\">CANCEL</button>                                      \n");
            out.write("                                    </td>                                   \n");
            out.write("                                </tr>\n");
            out.write("                            ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
